// Generates one `.env.<profile>.example` per deployment profile, plus the
// `env.manifest.json` handoff artifact (#15).
//
// Generated, never hand-maintained: a second list of the same variable names is
// exactly the duplicate declaration the kit's typesafety contract forbids. CI
// runs this with `--check`, which fails if the committed files are stale.
//
// It stops here on purpose. It does not emit GitHub Actions secret names,
// `vercel env` declarations or Terraform variable blocks — that is three
// emitters breaking whenever those formats shift, for names a cloner types once.
//
// One file per profile rather than one maximal file with everything commented
// out. A maximal file is friendlier to skim and actively lies: a cloner cannot
// tell required from irrelevant, which is the only thing the file exists to say.

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { PUBLIC_PHYSICAL_NAMES, publicSchema } from "@repo/env";
import { createLocalProfile } from "@repo/profiles";
import type { z } from "zod";

const profiles = [createLocalProfile()];

const SERVER_EXAMPLE_DIR = "apps/server";
const MANIFEST = "env.manifest.json";

const isRequired = (schema: z.ZodType) => !schema.safeParse(undefined).success;

type Entry = {
  name: string;
  required: boolean;
  public: boolean;
  profile: string | null;
  physical: { web: string; native: string } | null;
};

const serverEntries = (profile: (typeof profiles)[number]): Entry[] =>
  Object.entries(profile.serverSchema.shape)
    .map(([name, schema]) => ({
      name,
      required: isRequired(schema as z.ZodType),
      public: false,
      profile: profile.name,
      physical: null,
    }))
    .sort((a, b) => a.name.localeCompare(b.name));

const publicEntries = (): Entry[] =>
  Object.entries(publicSchema.shape)
    .map(([name, schema]) => ({
      name,
      required: isRequired(schema as z.ZodType),
      public: true,
      // A public variable belongs to every deployment, so it belongs to no
      // profile: it is app configuration, and no adapter ever has one.
      profile: null,
      physical: PUBLIC_PHYSICAL_NAMES[name as keyof typeof PUBLIC_PHYSICAL_NAMES],
    }))
    .sort((a, b) => a.name.localeCompare(b.name));

const exampleFor = (profile: (typeof profiles)[number]) => {
  const lines = [
    `# Generated by scripts/generate-env.ts — do not edit.`,
    `# Deployment profile: ${profile.name}`,
    `# Adapters: ${profile.fragments.map((one) => one.name).join(", ")}`,
    ``,
    ...serverEntries(profile).flatMap((entry) => [
      `# ${entry.required ? "required" : "optional"}`,
      `${entry.name}=`,
    ]),
  ];
  return `${lines.join("\n")}\n`;
};

const manifest = () =>
  `${JSON.stringify(
    {
      generatedBy: "scripts/generate-env.ts",
      entries: [...profiles.flatMap(serverEntries), ...publicEntries()],
    },
    null,
    2,
  )}\n`;

const outputs = new Map<string, string>([
  ...profiles.map(
    (profile) =>
      [join(SERVER_EXAMPLE_DIR, `.env.${profile.name}.example`), exampleFor(profile)] as const,
  ),
  [MANIFEST, manifest()],
]);

const check = process.argv.includes("--check");
const stale: string[] = [];

for (const [path, content] of outputs) {
  let existing: string | undefined;
  try {
    existing = readFileSync(path, "utf8");
  } catch {
    existing = undefined;
  }
  if (existing === content) continue;
  if (check) {
    stale.push(path);
    continue;
  }
  writeFileSync(path, content);
  console.log(`wrote ${path}`);
}

if (stale.length > 0) {
  console.error(
    `Env artifacts are stale. Run \`pnpm generate:env\` and commit:\n${stale
      .map((path) => `  - ${path}`)
      .join("\n")}\n`,
  );
  process.exit(1);
}

if (check) console.log(`Env artifacts up to date (${outputs.size} files).`);
